# Nexio课程表 - Gradle 全局构建参数
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
kotlin.code.style=official
android.useAndroidX=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
